### ISSUE TITLE
Card view documentation

### ISSUE THREAD

**Issue by christopherarter** [laravel/nova-docs#102]
> Cards are similar to resource tools, but are small, miniature tools that are typically displayed at the **top of your dashboard, resource index, or resource detail screens.** 

Where is this documented? I'm trying to display a card at the top of detail & edit forms.

**Comment by christopherarter** [comment]
I was able to use the methods documented for metrics to handle the hide / display logic
https://nova.laravel.com/docs/1.0/metrics/registering-metrics.html#resource-detail-metrics

There may want to be a bit more explicit section about handling card visibility.

**Comment by davidhemphill** [comment]
> To instruct a metric to be displayed on the detail page instead of the index page, chain the onlyOnDetail method onto your metric registration:

What would make it more explicit for you?
