### ISSUE TITLE
How to authenticate with Socialite instead?

### ISSUE THREAD

**Issue by jameslkingsley** [laravel/nova-docs#13]
Trying to get into Nova dashboard but my app uses Socialite for users, so there's no password. How can I implement my own login portal & logic to handle that?

On top of this my app is also using Laravel Passport to authenticate everything. I was hoping I'd be able to just specify who can use Nova based on a callback, instead of a full user login.

**Comment by jameslkingsley** [comment]
Okay so I managed to get passed login screen by doing the following:

**NovaServiceProvider:**
Commenting out the auth and password reset routes.
```php
Nova::routes()
    // ->withAuthenticationRoutes()
    // ->withPasswordResetRoutes()
    ->register();
```

**nova.php:**
Changing `web` to `api`, and commenting out auth middleware.
```php
'middleware' => [
    'api',
    // Authenticate::class,
    DispatchServingNovaEvent::class,
    BootTools::class,
    Authorize::class,
]
```

Now I'm getting a "non-object" error in `nova\partials\user.blade.php` as `auth()->user()` is `null`. I think for this to work with Passport the `user` would have to be passed in with the response, as it would get the user from the request using the access token - and then have a way of passing in that access token to all Nova requests. Not too sure tbh, but it would be great if there were native Passport authentication support for logging into Nova without a password, and instead using Socialite.

Luckily for now it seems `auth()->user()` is only used in `user.blade.php` so I'm just gonna edit that file and hope for the best.

**Comment by jameslkingsley** [comment]
Looks like a lot of classes reference the authenticated user for authorization so unfortunately Passport authentication simply cannot be used with Nova 😢

**Comment by jameslkingsley** [comment]
Moved to issues repo.

**Comment by phoenixg** [comment]
Have you solved this yet?
