### ISSUE TITLE
Missing in docs: What if you put your models in a folder?

### ISSUE THREAD

**Issue by Datalink-Wouter** [laravel/nova-docs#14]
When you use a folder for your models, you should change app/Nova/User.php:
public static $model = 'App\\User';
to
public static $model = 'App\\Models\\User';

It seems obvious but I think it's worth mentioning in the docs.

**Comment by axyr** [comment]
And it would be nice to be able to define the model in de generator:

```
php artisan nova:resource Venue --model=Models\\Venue
```

**Comment by MadMikeyB** [comment]
@axyr you can do :)

**Comment by axyr** [comment]
Ah man, I completely overlooked that...

I wanted too fast :).

**Comment by Datalink-Wouter** [comment]
#18
