### ISSUE TITLE
Document tailwind version or differences

### ISSUE THREAD

**Issue by jofrysutanto** [laravel/nova-docs#140]
While we do have reference to Tailwind [here](https://nova.laravel.com/docs/1.0/customization/frontend.html#css), people would expect that the entire Tailwind css is readily usable in Nova. 

However, text colours variant (e.g. `text-dark-green`) isn't available within Nova; though this is documented in tailwind: https://tailwindcss.com/docs/text-color

I am not entirely sure if this is due to different version of Tailwind, or these are excluded from Nova — but it will definitely be handy to be documented.

**Comment by davidhemphill** [comment]
Tailwind is for designing **custom** user interfaces. The Tailwind configuration file is designed to be customized and optimized for individual use-cases. Don't see a need to reinforce that inside the documentation at this time.

**Comment by jofrysutanto** [comment]
Definitely agree with the notion that Tailwind is meant to be customised and optimised to fit individual use cases; same with the need to reinforce that in the documentation. Though I do feel that the following excerpt from the documentation:

```
... you are free to leverage all Tailwind features and classes that are needed by your custom components
```

seem to be a bit misleading for those who are looking to find built-in ways to style Nova. Then again, it's just my two cents, and it is probably too much of a muchness at this stage. Awesome work by the way, cheers.

**Comment by davidhemphill** [comment]
Yeah, we could probably update that language to be a little clearer that we're using a customized version of the default Tailwind config.

**Comment by goyote** [comment]
@jofrysutanto what was the solution to this?

**Comment by jofrysutanto** [comment]
Unfortunately, we ended up inlining the style using HTML tag when returning value to nova — isn't the cleanest way, but it does the job.
