### ISSUE TITLE
Missing methods for policies when there's a relationship

### ISSUE THREAD

**Issue by denismarinov** [laravel/nova-docs#146]
I am referring to this in the documentation:
https://nova.laravel.com/docs/1.0/resources/authorization.html#policies

Since there's and ``add{Model}`` method, I cannot figure out anything about ``delete{Model}`` and ``edit/update{Model}`` methods. Is there something like that by some change?

And would be greatly appreciated if all this is included in the docs.

Thanks

**Comment by davidhemphill** [comment]
As Nova uses Laravel's built-in policies, these are covered inside those docs: https://laravel.com/docs/5.7/authorization#creating-policies. It'd be redundant to cover them in our own.
