### ISSUE TITLE
Grammatical error under Authenticating Nova in Continuous Integration (CI) Environments

### ISSUE THREAD

**Issue by lesaff** [laravel/nova-docs#151]
https://nova.laravel.com/docs/2.0/installation.html#authenticating-nova-in-continuous-integration-ci-environments

`advised` should be changed to `advisable`

First paragraph, first sentence:
> It's not *advised* to store your auth.json file inside your project's version control repository. However, ...

I think it should be
> It is not *advisable* to store your auth.json file inside your project's version control repository. However, ...

**Comment by davidhemphill** [comment]
https://english.stackexchange.com/questions/379952/is-it-ok-to-say-is-not-advised
