### ISSUE TITLE
How to serve it on laravel valet? After i build im getting error

### ISSUE THREAD

**Issue by codeitlikemiley** [laravel/nova-docs#169]
I tried other vue related documentation , and serve it on laravel valet so i can used it locally, when i have no internet.

Yes i can run here yarn start , but i dont wanna spin another server just to run this offline documentation.

If there is a way to make it work with valet so i can use it locally that would be awesome thanks

**Comment by davidhemphill** [comment]
You can run the included `docs:build` command and serve the output using Laravel Valet.
