### ISSUE TITLE
Custom field attributes

### ISSUE THREAD

**Issue by axyr** [laravel/nova-docs#17]
I could not find another place to ask nova related questions / suggestions, so I leave it here.

Please correct me, if there is a better place to ask this:

I cant' see a way to set field attributes like `readonly` or `disabled` in the Resource classes.

I was looking for something like:

`Currency::make('Price')->readonly($someBoolean)`

or maybe even more flexible:

`Currency::make('Price')->setAttribute( 'disabled', $someBoolean)`

Or am I missing something?

**Comment by axyr** [comment]
Policies have nothing to do with setting field attributes.

**Comment by v1nk0** [comment]
@reganjohnson policies can define if a user can see the field or not, not that the field is readonly.

Issue tracker can be found here: https://github.com/laravel/nova-issues/issues

For people landing on this page, the accompanying issue (or better said _feature request_) can be found here: https://github.com/laravel/nova-issues/issues/19

**Comment by davidhemphill** [comment]
Yes, please post this feature request over here: https://github.com/laravel/nova-issues/issues
