### ISSUE TITLE
"Read More" links in release note is pointing to a private github repo

### ISSUE THREAD

**Issue by BinotaLIU** [laravel/nova-docs#173]
On releases page: https://nova.laravel.com/releases

v2.0.6 release note contains two links that is pointing to a private github repository: https://github.com/laravel/nova

**Comment by davidhemphill** [comment]
This is not related to the Nova docs repo at all.

**Comment by daniel-de-wit** [comment]
@davidhemphill Where do you suggest this issue should be posted instead?

**Comment by dillingham** [comment]
@BinotaLIU @daniel-de-wit https://nova.laravel.com/settings#github
