### ISSUE TITLE
The requested package laravel/nova could not be found in any version

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-docs#22]
When I add the "laravel/nova" pakages as described in the documentation: 

**Next, add laravel/nova to the require section of your composer.json file:**

`"require": {
    "php": "^7.1.3",
    "fideloper/proxy": "^4.0",
    "laravel/framework": "5.6.*",
    "laravel/nova": "*"
}`

I'm receiving this error during a composer update.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/10268813/44506618-866f7200-a6a7-11e8-9152-b333099add78.png">

**Comment by MadMikeyB** [comment]
```
"minimum-stability": "dev",
"prefer-stable": true,
```

Add these to composer.json and try again.

**Comment by StanBarrows** [comment]
@MadMikeyB Same here, 

this code is alrdy part of the default package

**Comment by raakesh** [comment]
@StanBarrows 
I got it working.

Here is my composer.json
[composer.json gist](https://gist.github.com/raakesh/26725f6298c53a54fdb4857a37a3e510)

**Comment by StanBarrows** [comment]
@raakesh 

I copy pasted your file. With the same results.. No idea behind this..

**Comment by raakesh** [comment]
Try it again with new laravel installation. (Btw I used Nova v1.05 ).

**Comment by tomhatzer** [comment]
@StanBarrows is your nova directory in the same folder as your laravel app? You have to check the path in the "repositories" entry, if nova is not in the same directory as your composer.json from laravel, you need to customize ./nova in there. You can also set absolute paths to your nova folder.

**Comment by themsaid** [comment]
try `dev-master` instead of `*` if you're on windows.

**Comment by StanBarrows** [comment]
@raakesh That worked out this time!

Thanks everyone else for the help and their suggestions!

**Comment by Livijn** [comment]
Using `dev-master` instead of `*` fixed it for me. Thanks @themsaid

**Comment by antonioribeiro** [comment]
Had the same error on macOS. If anyone get this again you can try to 

- remove nova from composer.json
- composer update
- re-add nova
- composer update

**Comment by yosuawinata** [comment]
> Had the same error on macOS. If anyone get this again you can try to
> 
> * remove nova from the require section of composer.json
> * composer update
> * re-add nova
> * composer update

I did, but the error is still displayed. my nova version is 1.0.16. Any advise ?

**Comment by connor11528** [comment]
You need to be running at least Laravel 5.6 for Nova install to work. That was my issue that got this error

**Comment by hamdongunner** [comment]
I found out that the version of the Nova file is a little bit old, I've changed the laravel/framework 
from
`"laravel/framework": "5.8.*",`
to
`"laravel/framework": "5.7.*",`
And it worked!
