### ISSUE TITLE
Nova field Currency::make('Price') doesnt work on Windows. 

### ISSUE THREAD

**Issue by julianpoma** [laravel/nova-docs#35]
When you try to use the Currency field, if you are developing on windows, it throws an error:

![image](https://user-images.githubusercontent.com/19490445/44551749-72a32a80-a6fe-11e8-8efc-b06f877ac82a.png)

This function is not available on Windows systems. [Check the PHP doc
](https://secure.php.net/manual/en/function.money-format.php)

> Note:
> The function money_format() is only defined if the system has strfmon capabilities. For example, Windows does not, so money_format() is undefined in Windows.

I open this issue so you can add a little note on the doc, for other people developing on windows based systems.

An alternative to the Currency field would be using a default Number field, with a modifier like this

```
Number::make('Debt')
                ->resolveUsing(function ($value) {
                    return '$'.$value
                }),
```

**Comment by brandc87** [comment]
Using your alternative doesn't fill in the field when it comes to edits (on windows) it leaves the field blank.

**Comment by julianpoma** [comment]
@brandc87 @astr0naugh7 Hi guys. For the time being, I am using [https://github.com/vyuldashev/nova-money-field](this package) as a replacement of the default Currency::field. It works really well on my Windows 10 env and has nice features like Location and MinorUnits support (storing the currency as integer)

**Comment by astr0naugh7** [comment]
> @brandc87 @astr0naugh7 Hi guys. For the time being, I am using [this package](https://github.com/vyuldashev/nova-money-field) as a replacement of the default Currency::field. It works really well on my Windows 10 env and has nice features like Location and MinorUnits support (storing the currency as integer)

Hey thanks, I'll check that out. Great idea.

**Comment by davidhemphill** [comment]
This is for nova documentation bug. Please open a new issue on https://github.com/laravel/nova for bug reports.
