### ISSUE TITLE
Doc section js files disappear from server, requiring reload

### ISSUE THREAD

**Issue by jwjcmw** [laravel/nova-docs#40]
I guess this is really just a artifact of using vuepress, but I keep on having instances where I click on a section of the docs and it just acts like it is going to load, but never does (there is a 404 in the network tab looking for a fingerprinted js file), while the other sections are still working fine.  You have to reload the whole page to get the new section references.  I assume this is because you are pushing updates out pretty often.  I don't know if there is anyway around this, and it likely won't be as much of an issue once you get past the fire drill you are going through now.

**Comment by davidhemphill** [comment]
Going to close this, as there's not a specific way to test this.
