### ISSUE TITLE
file fields customization docs problem

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-docs#49]
samples from [Customizing Previews and Thumbnails](https://nova.laravel.com/docs/1.0/resources/file-fields.html#customization) need to be updated because `you may access the field's underlying column value via $this->value` is not true and the examples will not works.

**Comment by davidhemphill** [comment]
If you think there's a bug please post it over at laravel/nova-issues.

**Comment by jBOKA** [comment]
@davidhemphill The bug is fixed. Docs need update
PR: https://github.com/laravel/nova-docs/pull/123
