### ISSUE TITLE
This <Model> may not be associated with this resource.

### ISSUE THREAD

**Issue by Jasperrr91** [laravel/nova-docs#50]
So I have a Model called `Booking` and two models called `Delivery` and `Pickup`. Each `Booking` has at most one `Delivery` and at most one `Pickup`.

This is simply defined as follows for the `Booking` model:
```php
/**
     * Get the delivery that belongs to this booking.
     */
    public function delivery()
    {
        return $this->hasOne('App\Delivery');
    }

    /**
     * Get the pickup that belongs to this booking.
     */
    public function pickup()
    {
        return $this->hasOne('App\Pickup');
    }
```

And as follows for both the `Pickup` as the `Delivery` model:
```php
/**
     * Get the booking that owns the delivery.
     */
    public function booking()
    {
        return $this->belongsTo('App\Booking');
    }
```

In my Nova resource for `Delivery`/`Pickup`, I have the following fields:
```php
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Street')->sortable(),
            Text::make('City')->sortable(),
            DateTime::make('planned_time')->sortable(),
            BelongsTo::make('Booking')->sortable(),
        ];
    }
```

This works alright, the id of the related `Booking` model is shown. However, when I try to edit the `Delivery` resource, I get hit by an error message upon saving:
`This booking may not be associated with this resource.`

This should not be happening. Any idea why this error occurs?

On a separate note, a feature request. I would LOVE if we were able to actually include fields from the related model, on the resource index/edit page. That would make stuff 10x easier.

**Comment by judge2020** [comment]
Getting the same issue. Looks like the `relationshipIsFull` method (in src/Rules/Relatable) doesn't take into account editing the single resource in the `HasOne` relationship:

```php
return $inverseRelation &&
       $model->{$inverseRelation->attribute}()->count() > 0;
```

Note: this should have been an issue over at https://github.com/laravel/nova-issues.

**Comment by Jasperrr91** [comment]
Sweet, thanks @judge2020! I completely missed that there is a separate Nova-Issues git, I'll post future issues over there.

**Comment by IwishSystem** [comment]
Is there a fix to it? How have you doing guys to overcome this problem?
