### ISSUE TITLE
Suggested addition to BelongsTo documentation

### ISSUE THREAD

**Issue by justincone** [laravel/nova-docs#51]
# Problem
[The docs for `BelongsTo`](https://nova.laravel.com/docs/1.0/resources/relationships.html#belongsto) don't currently explain all three arguments available for the method.

## Solution 
Include an example and explanation like this one:

```php
BelongsTo::make('Home Club', 'homeClub', 'App\Nova\Club');
```

Argument 1: Name to display (e.g. Home Club)
Argument 2: Name of the relationship as used in the model (e.g. club)
Argument 3: The Nova Resource (e.g. App\Nova\Club)

(Taken from https://github.com/laravel/nova-issues/issues/179#issuecomment-415965401)

**Comment by ok200paul** [comment]
Ah - I've just seen this after I submitted https://github.com/laravel/nova-docs/pull/61 - hope it helps.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
