### ISSUE TITLE
Add User Creation Help

### ISSUE THREAD

**Issue by alexfinnarn** [laravel/nova-docs#57]
On https://nova.laravel.com/docs/1.0/installation.html#installing-nova

"That's it! Next, you may navigate to your application's /nova path in your browser and you should be greeted with the Nova dashboard which includes links to various parts of this documentation."

No, that is not it...I had no users in my table after the migrations and nothing for seeding. I did see the `php artisan nova:user` command which allowed me to generate a user and login, though.

**Comment by 4unkur** [comment]
Thanks man. It helped

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
