### ISSUE TITLE
Undefined method asHtml() 

### ISSUE THREAD

**Issue by JasonMortonNZ** [laravel/nova-docs#69]
As per the documentation I've tried creating a field that needed to contain HTML but it appears the `->asHtml()`method is undefined. I was using the `Laravel\Nova\Fields\Text` class.

Reference to this method in the documentation: [Computed Fields](https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields)

**Comment by davidhemphill** [comment]
This repo isn't for support.
