### ISSUE TITLE
Add to Docs: Moving from .zip to Composer installation

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-docs#76]
This was a bit troublesome. I got it working after a bit of trial/error, but a clear step-by-step may help others.

**Comment by davidhemphill** [comment]
We already have documentation on using Composer. Switching methods is simply a matter of deleting the old /nova folder and updating your `composer.json` to the values in the documentation.

**Comment by rdrnnr87** [comment]
@noahlocke would be interested to know any tips you have on switching from zip to composer.  I too did not find it to be as easy as deleting /nova and updating `composer.json`.

I found that any Nova specific packages also had to be uninstalled as they immediately had unmet dependencies.  Also had to remove NovaServiceProvider from `config/app.php`.  After all this still couldn't get it to work.  Hung up on composer error "[RuntimeException] vendor does not exist and could not be created."  Thinking this may have to do with the nova symlink in /vendor/laravel but I already gave up and went back to the zip route for now.

**Comment by noahlocke** [comment]
@rdrnnr87 sorry man, I wish I could remember. All I do remember is that is was a huge pain, and the documentation @davidhemphill mentioned are not sufficient. I think it's one of those things that us early adopters will just have to deal with, as I don't image new Nova customers will be using the .zip at all.

**Comment by rdrnnr87** [comment]
For anyone who runs across this post, I got it to work and it's pretty much as easy as @davidhemphill says.  The one additional step I had to do was delete nova symlink in /vendor/laravel.
