### ISSUE TITLE
Nova is not shown correctly, it appears without design

### ISSUE THREAD

**Issue by MalkSof** [laravel/nova-docs#81]
![image](https://user-images.githubusercontent.com/42155335/46484172-995d8200-c7cf-11e8-8c20-0b956957ee92.png)

![image](https://user-images.githubusercontent.com/42155335/46484225-b6925080-c7cf-11e8-979b-63e473a4f996.png)

**Comment by davidhemphill** [comment]
This isn't a support request forum. This is for issues related to the documentation.
