### ISSUE TITLE
What browsers are officially supported?

### ISSUE THREAD

**Issue by t2thec** [laravel/nova-docs#88]
I am just trying to find out what browser are officially supported.

We have found issues on older browsers (Good old IE10) and not sure if these should be reported.

Would it be possible to get a section in the docs that spells it out for us?

Thanks guys.

**Comment by dillingham** [comment]
A lot of clients proposals outline browser support. I know initially intended for developers who use modern browsers, but a larger amount seem to be opening it up to clients / end users so it would be nice to know. I currently have a few proposals that say IE 10 / Edge support :/

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
