### ISSUE TITLE
How to render the content from a Markdown field?

### ISSUE THREAD

**Issue by connor11528** [laravel/nova-docs#89]
I am creating a blog using Laravel Nova. The body for each blog post has a Laravel Nova markdown field. In the [fields documentation](https://nova.laravel.com/docs/1.0/resources/fields.html#field-types) it says:

> The Markdown field will store the raw Markdown text within the associated database column

How can I render the formatted markdown in a blade view? It would be helpful to show users how to display the markdown we store. Do we need to install something new to render formatted markdown in blade views?

**Comment by dillingham** [comment]
@connor11528 this is not a place for personal questions un related to nova documentation and unrelated to nova as a whole. In the future please ask questions via [laracasts forum
](https://laracasts.com/discuss/channels/nova)
To answer your question though:

```php
 {{ Illuminate\Mail\Markdown::parse($markdown) }}
```

**Comment by connor11528** [comment]
Okay thanks @davidhemphill. I do think it'd be helpful to have a note in the fields section about how to use the raw markdown within a blade view after it's stored. This worked great

**Comment by connor11528** [comment]
Solution:

```
use Illuminate\Mail\Markdown;
...
public function show(Post $post)
{
    $markdown = Markdown::parse($post->body);
    return view('blog.post', compact('post', 'markdown'));
}
```
