### ISSUE TITLE
Unable to Update Resources: the server responded with a status of 419

### ISSUE THREAD

**Issue by astr0naugh7** [laravel/nova-docs#91]
Chrome Dev Tools when trying to update a Resource: 

Failed to load resource: the server responded with a status of 419 (unknown status) -----------  :8000/nova-api/loans/2:1

Loan ID 2 as you can see above. Don't make any changes to the actual Resource, "Update" works. Change anything, I click the Update, I get that error across all Resources. 

Any idea? Searched this problem with no results. 

Laravel 5.7 (Upgraded from 5.6) Php 7.2, XAMPP (Production is nginx). 

Please advise.

**Comment by davidhemphill** [comment]
This repo is for the Nova documentation. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
